<?php

namespace AppBundle\Repository;

/**
 * BeberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeberRepository extends \Doctrine\ORM\EntityRepository
{
}
