<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    public function FindAllJson()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT l FROM AppBundle:Location l'
            )
            ->getResult(Query::HYDRATE_ARRAY);
    }


}
